### ISSUE TITLE
reserved name issue when cloning

### ISSUE THREAD

**Issue by thorizer** [Doha26/Instagram-clone#1]
aux is a reserved name on Windows. I'm getting errors when cloning. 
you're most likely working on a mac but you should rename it to something else. (src/containers/ Aux)

**Comment by Doha26** [comment]
Hi @thorizer. Effectively I'm working on a Mac. So I have updated the component and renamed it to AuxHOC since it's a Higher Order Component.  Should fi the issue on windows.

**Comment by thorizer** [comment]
@Doha26 great. thanks ! 
You have the same issue on your facebook clone btw.

**Comment by Doha26** [comment]
I just fixed the issue for Facebook clone. let me know if solved and I will close this issue.
