### ISSUE TITLE
'src/containers/Aux': Invalid argument

### ISSUE THREAD

**Issue by Simoneth** [Doha26/Instagram-clone#3]
Hi,
I'm on Win10 and I got this:
```
fatal: cannot create directory at 'src/containers/Aux': Invalid argument
warning: Clone succeeded, but checkout failed.
```
Notice that in Win you cannot name a folder Aux, it's reserved for legacy reasons.

**Comment by Doha26** [comment]
Hi Simoneth, 

i have fixed this issue for windows enviroment. i have renamed the Aux component to AuxHOC because it's a Higher Order Component. try to pull the last version on the branch Master and see if the problem persist. 

Regards
