### ISSUE TITLE
can't clone repo

### ISSUE THREAD

**Issue by WizardSource** [Doha26/Instagram-clone#4]
when runnning 

 $ git clone https://github.com/Doha26/InstagramClone.git
 
 $ cd InstagramClone
 
 $ npm install
 
 $ react-native run-ios
 

```
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening InstagramClone.xcworkspace. Run CLI with --verbose flag for more details.
Prepare build
note: Using legacy build system
=== BUILD TARGET InstagramClone OF PROJECT InstagramClone WITH CONFIGURATION Debug ===

Check dependencies
The file “Pods-InstagramClone.debug.xcconfig” couldn’t be opened because there is no such file. (/Users/cliffkyanne/InstagramClone/ios/Pods/Target Support Files/Pods-InstagramClone/Pods-InstagramClone.debug.xcconfig)

PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /Users/cliffkyanne/Library/Developer/Xcode/DerivedData/InstagramClone-buttocxmfsowvqbpqjbrojrozidb/Build/Intermediates.noindex/InstagramClone.build/Debug-iphonesimulator/InstagramClone.build/Script-43DE2BB8B1110D5D511C086C.sh
    cd /Users/cliffkyanne/InstagramClone/ios
    /bin/sh -c /Users/cliffkyanne/Library/Developer/Xcode/DerivedData/InstagramClone-buttocxmfsowvqbpqjbrojrozidb/Build/Intermediates.noindex/InstagramClone.build/Debug-iphonesimulator/InstagramClone.build/Script-43DE2BB8B1110D5D511C086C.sh
diff: /Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.


** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution [CP]\ Check\ Pods\ Manifest.lock /Users/cliffkyanne/Library/Developer/Xcode/DerivedData/InstagramClone-buttocxmfsowvqbpqjbrojrozidb/Build/Intermediates.noindex/InstagramClone.build/Debug-iphonesimulator/InstagramClone.build/Script-43DE2BB8B1110D5D511C086C.sh
(1 failure)

```

**Comment by Doha26** [comment]
Hi , 
it seems to be a problem with pods. project use Pods as you can see a Podfile in the "ios"  folder. 
at the root of the project, run this. 

- cd ios && pod install &&  cd..
- react-native run-ios 

thanks. for your return. i will update the readme to add the "pod install" command.
Let me know if everything okay

**Comment by WizardSource** [comment]
Hi, Doha 


Error occurs when running: 

- cd ios && pod install && cd..

```
w $cd ios && pod install && cd..

Detected React Native module pods for BVLinearGradient, RNGestureHandler, RNReanimated, RNSVG, RNVectorIcons, react-native-blur, react-native-camera, react-native-cameraroll, react-native-fetch-blob, and react-native-video
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `Folly` from `../node_modules/react-native/third-party-podspecs/Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
[!] CocoaPods could not find compatible versions for pod "React/Core":
  In Podfile:
    react-native-fetch-blob (from `../node_modules/react-native-fetch-blob`) was resolved to 0.10.6, which depends on
      React/Core

None of your spec sources contain a spec satisfying the dependency: `React/Core`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

```

**Comment by Doha26** [comment]
Hi, 
the error is pretty clear i think.
may be an out-of-date version of cocoapods installed on your local machine. 
try this : 

- pod update && pod install

**Comment by WizardSource** [comment]
Thanks for all your help and prompt replies.

I ran the updates and now simulator is launching but still failing 
<img width="798" alt="Screen Shot 2020-03-11 at 2 36 54 PM" src="https://user-images.githubusercontent.com/7276145/76452183-1454a000-63a7-11ea-85b2-7fc52492f9f8.png">

**Comment by Doha26** [comment]
Hi, 

seems to also been a problem with your Pods. 
- try update your cocoapods gobaly with `brew upgrade cocoapods `. 
- run pod `deintegrate && pod install`  inside the ios folder. 
- then `react-native run-ios` at the root .

**Comment by Doha26** [comment]
Hi, 
is everything work fine ? so can we close this issue ?

**Comment by WizardSource** [comment]
I didn't want to be a nuisance, I was not able to get it working. I tried every "solution" I could find from people having similar issues.

the furthest I was able to get upon running :

- try update your cocoapods gobaly with `brew upgrade cocoapods .`
- run pod `deintegrate && pod install` inside the ios folder.
- then `react-native run-ios --simulator="iPhone 11"` at the root .

- 

`error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening I

nstagramClone.xcworkspace. Run CLI with --verbose flag for more details.
User defaults from command line:
    IDEDerivedDataPathOverride = /Users/cliffkyanne/InstagramClone/ios/build/InstagramClone

Prepare build
note: Using legacy build system
=== BUILD TARGET InstagramClone OF PROJECT InstagramClone WITH CONFIGURATION Debug ===

Check dependencies

PhaseScriptExecution Start\ Packager build/InstagramClone/Build/Intermediates.noindex/InstagramClone.build/Debug-iphonesimulator/InstagramClone.build/Script-FD10A7F022414F080027D42C.sh
    cd /Users/cliffkyanne/InstagramClone/ios
    /bin/sh -c /Users/cliffkyanne/InstagramClone/ios/build/InstagramClone/Build/Intermediates.noindex/InstagramClone.build/Debug-iphonesimulator/InstagramClone.build/Script-FD10A7F022414F080027D42C.sh
Connection to localhost port 8081 [tcp/sunproxyadmin] succeeded!

CompileC build/InstagramClone/Build/Intermediates.noindex/InstagramClone.build/Debug-iphonesimulator/InstagramClone.build/Objects-normal/x86_64/main.o InstagramClone/main.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/cliffkyanne/InstagramClone/ios
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/cliffkyanne/.rbenv/shims:/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/cliffkyanne/flutter/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -target x86_64-apple-ios9.0-simulator -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/cliffkyanne/InstagramClone/ios/build/InstagramClone/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/cliffkyanne/InstagramClone/ios/build/InstagramClone/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -fobjc-abi-version=2 -fobjc-legacy-dispatch -index-store-path /Users/cliffkyanne/InstagramClone/ios/build/InstagramClone/Index/DataStore -iquote /Users/cliffkyanne/InstagramClone/ios/build/InstagramClone/Build/Intermediates.noindex/InstagramClone.build/Debug-iphonesimulator/InstagramClone.build/InstagramClone-generated-files.hmap -I/Users/cliffkyanne/InstagramClone/ios/build/InstagramClone/Build/Intermediates.noindex/InstagramClone.build/Debug-iphonesimulator/InstagramClone.build/InstagramClone-own-target-headers.hmap -I/Users/cliffkyanne/InstagramClone/ios/build/InstagramClone/Build/Intermediates.noindex/InstagramClone.build/Debug-iphonesimulator/InstagramClone.build/InstagramClone-all-target-headers.hmap -iquote /Users/cliffkyanne/InstagramClone/ios/build/InstagramClone/Build/Intermediates.noindex/InstagramClone.build/Debug-iphonesimulator/InstagramClone.build/InstagramClone-project-headers.hmap -I/Users/cliffkyanne/InstagramClone/ios/build/InstagramClone/Build/Products/Debug-iphonesimulator/include -I/Users/cliffkyanne/InstagramClone/ios/build/InstagramClone/Build/Intermediates.noindex/InstagramClone.build/Debug-iphonesimulator/InstagramClone.build/DerivedSources-normal/x86_64 -I/Users/cliffkyanne/InstagramClone/ios/build/InstagramClone/Build/Intermediates.noindex/InstagramClone.build/Debug-iphonesimulator/InstagramClone.build/DerivedSources/x86_64 -I/Users/cliffkyanne/InstagramClone/ios/build/InstagramClone/Build/Intermediates.noindex/InstagramClone.build/Debug-iphonesimulator/InstagramClone.build/DerivedSources -F/Users/cliffkyanne/InstagramClone/ios/build/InstagramClone/Build/Products/Debug-iphonesimulator -MMD -MT dependencies -MF /Users/cliffkyanne/InstagramClone/ios/build/InstagramClone/Build/Intermediates.noindex/InstagramClone.build/Debug-iphonesimulator/InstagramClone.build/Objects-normal/x86_64/main.d --serialize-diagnostics /Users/cliffkyanne/InstagramClone/ios/build/InstagramClone/Build/Intermediates.noindex/InstagramClone.build/Debug-iphonesimulator/InstagramClone.build/Objects-normal/x86_64/main.dia -c /Users/cliffkyanne/InstagramClone/ios/InstagramClone/main.m -o /Users/cliffkyanne/InstagramClone/ios/build/InstagramClone/Build/Intermediates.noindex/InstagramClone.build/Debug-iphonesimulator/InstagramClone.build/Objects-normal/x86_64/main.o
In file included from /Users/cliffkyanne/InstagramClone/ios/InstagramClone/main.m:10:
/Users/cliffkyanne/InstagramClone/ios/InstagramClone/AppDelegate.h:8:9: fatal error: 'React/RCTBridgeDelegate.h' file not found
#import <React/RCTBridgeDelegate.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

CompileC build/InstagramClone/Build/Intermediates.noindex/InstagramClone.build/Debug-iphonesimulator/InstagramClone.build/Objects-normal/x86_64/AppDelegate.o InstagramClone/AppDelegate.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/cliffkyanne/InstagramClone/ios
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/cliffkyanne/.rbenv/shims:/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/cliffkyanne/flutter/bin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -target x86_64-apple-ios9.0-simulator -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=gnu99 -fobjc-arc -fmodules -gmodules -fmodules-cache-path=/Users/cliffkyanne/InstagramClone/ios/build/InstagramClone/ModuleCache.noindex -fmodules-prune-interval=86400 -fmodules-prune-after=345600 -fbuild-session-file=/Users/cliffkyanne/InstagramClone/ios/build/InstagramClone/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror=non-modular-include-in-framework-module -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror=return-type -Wunreachable-code -Wno-implicit-atomic-properties -Werror=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DDEBUG=1 -DOBJC_OLD_DISPATCH_PROTOTYPES=0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.2.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -fobjc-abi-version=2 -fobjc-legacy-dispatch -index-store-path /Users/cliffkyanne/InstagramClone/ios/build/InstagramClone/Index/DataStore -iquote /Users/cliffkyanne/InstagramClone/ios/build/InstagramClone/Build/Intermediates.noindex/InstagramClone.build/Debug-iphonesimulator/InstagramClone.build/InstagramClone-generated-files.hmap -I/Users/cliffkyanne/InstagramClone/ios/build/InstagramClone/Build/Intermediates.noindex/InstagramClone.build/Debug-iphonesimulator/InstagramClone.build/InstagramClone-own-target-headers.hmap -I/Users/cliffkyanne/InstagramClone/ios/build/InstagramClone/Build/Intermediates.noindex/InstagramClone.build/Debug-iphonesimulator/InstagramClone.build/InstagramClone-all-target-headers.hmap -iquote /Users/cliffkyanne/InstagramClone/ios/build/InstagramClone/Build/Intermediates.noindex/InstagramClone.build/Debug-iphonesimulator/InstagramClone.build/InstagramClone-project-headers.hmap -I/Users/cliffkyanne/InstagramClone/ios/build/InstagramClone/Build/Products/Debug-iphonesimulator/include -I/Users/cliffkyanne/InstagramClone/ios/build/InstagramClone/Build/Intermediates.noindex/InstagramClone.build/Debug-iphonesimulator/InstagramClone.build/DerivedSources-normal/x86_64 -I/Users/cliffkyanne/InstagramClone/ios/build/InstagramClone/Build/Intermediates.noindex/InstagramClone.build/Debug-iphonesimulator/InstagramClone.build/DerivedSources/x86_64 -I/Users/cliffkyanne/InstagramClone/ios/build/InstagramClone/Build/Intermediates.noindex/InstagramClone.build/Debug-iphonesimulator/InstagramClone.build/DerivedSources -F/Users/cliffkyanne/InstagramClone/ios/build/InstagramClone/Build/Products/Debug-iphonesimulator -MMD -MT dependencies -MF /Users/cliffkyanne/InstagramClone/ios/build/InstagramClone/Build/Intermediates.noindex/InstagramClone.build/Debug-iphonesimulator/InstagramClone.build/Objects-normal/x86_64/AppDelegate.d --serialize-diagnostics /Users/cliffkyanne/InstagramClone/ios/build/InstagramClone/Build/Intermediates.noindex/InstagramClone.build/Debug-iphonesimulator/InstagramClone.build/Objects-normal/x86_64/AppDelegate.dia -c /Users/cliffkyanne/InstagramClone/ios/InstagramClone/AppDelegate.m -o /Users/cliffkyanne/InstagramClone/ios/build/InstagramClone/Build/Intermediates.noindex/InstagramClone.build/Debug-iphonesimulator/InstagramClone.build/Objects-normal/x86_64/AppDelegate.o
In file included from /Users/cliffkyanne/InstagramClone/ios/InstagramClone/AppDelegate.m:8:
/Users/cliffkyanne/InstagramClone/ios/InstagramClone/AppDelegate.h:8:9: fatal error: 'React/RCTBridgeDelegate.h' file not found
#import <React/RCTBridgeDelegate.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~


** BUILD FAILED **


**The following build commands failed:
	CompileC build/InstagramClone/Build/Intermediates.noindex/InstagramClone.build/Debug-iphonesimulator/InstagramClone.build/Objects-normal/x86_64/main.o InstagramClone/main.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)**


`

**Comment by Doha26** [comment]
Hi,

Previous steps fix issues related to dépendances.

Now Error ask you to try building with the XCode app. Look like command line build has some problem with some imports. 

- open XCode 
- go to the iOS folder 
- open InstagramClone.xcworkspace in Xcode and build.

**Comment by WizardSource** [comment]
Thanks for your patience and all your replies. I just can't make this work spent too many hours attempting to figure it out. I don't think it has anything to do with your project just something not going right on my end.  I'm going to spend some time away from it, and i'll try to resolve it later. You could close the issue.

**Comment by Doha26** [comment]
Hi,

Alright. I had been able to follow the same steps on my local machine and run the app without any issue. 

You also need to be familiar with xcode to well understand errors and fix them quickly otherwise you will spend weeks trying to fix something may be simple. 

Regards.
